# The URL the site will be built for
base_url = "https://hollowden.xyz"

# Site Title
title = "Hollow Den"

# Site Description
description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "emily_zola_theme"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# Author name, appears in footer.
emily_author = "Holly"

# Path to the header icon / favicon image.
# Please save image to static/images
emily_icon = "/images/logo.png"

emily_favicon = "/images/favicon.png"

# header icon width.
# height will be automatically rendered.
emily_iconsize = 70

# number of posts in index.html.
emily_indexposts = 5

# switch to dark-theme
emily_dark_mode = true

# show theme-toggler
emily_theme_toggler = true

emily_archives_title = "Posts"
emily_about_title = "Acerca de"